//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control.Globalization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIGlobalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIGlobalization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Control.Globalization.UIGlobalization", typeof(UIGlobalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calories calculated:
        ///.
        /// </summary>
        public static string CaloriesAlert {
            get {
                return ResourceManager.GetString("CaloriesAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carbohydrates.
        /// </summary>
        public static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command:.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date ordered.
        /// </summary>
        public static string DateOrdered {
            get {
                return ResourceManager.GetString("DateOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. - get dish by Id;
        ///2. - get all dishes;
        ///3. - add dish;
        ///4. - remove dish by Id;
        ///5. - edit dish;
        ///0. - return to home screen.
        ///.
        /// </summary>
        public static string DishGetCommands {
            get {
                return ResourceManager.GetString("DishGetCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dish name.
        /// </summary>
        public static string DishName {
            get {
                return ResourceManager.GetString("DishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fat.
        /// </summary>
        public static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///1. - get visitor by Id;
        ///2. - get all visitors;
        ///3. - add visitor;
        ///4. - remove visitor by Id;
        ///5. - edit visitor;
        ///6. - calculate calories(Format: VisitorId|RecieptDate);
        ///
        ///0. - return to home screen.
        ///.
        /// </summary>
        public static string FitnessGetCommands {
            get {
                return ResourceManager.GetString("FitnessGetCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FitnessController
        ///
        ///(Body format: Id|Name|Height|Weight)
        ///.
        /// </summary>
        public static string FitnessInputHeader {
            get {
                return ResourceManager.GetString("FitnessInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect command!
        ///.
        /// </summary>
        public static string IncorrectCommand {
            get {
                return ResourceManager.GetString("IncorrectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect format.
        ///Try again.
        ///.
        /// </summary>
        public static string IncorrectFormatAlert {
            get {
                return ResourceManager.GetString("IncorrectFormatAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect IDs.
        ///Try again.
        ///.
        /// </summary>
        public static string IncorrectIdAlert {
            get {
                return ResourceManager.GetString("IncorrectIdAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KitchenController
        ///
        ///(Body format: Id|Name|Price|Product Ids)
        ///Product Ids are separated by commas
        ///
        ///.
        /// </summary>
        public static string KitchenInputHeader {
            get {
                return ResourceManager.GetString("KitchenInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Objects info:
        ///.
        /// </summary>
        public static string ListGetAlert {
            get {
                return ResourceManager.GetString("ListGetAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Obect was successfully created:
        ///.
        /// </summary>
        public static string ObjectAddAlert {
            get {
                return ResourceManager.GetString("ObjectAddAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Obect was successfully changed:
        ///.
        /// </summary>
        public static string ObjectChangeAlert {
            get {
                return ResourceManager.GetString("ObjectChangeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object info:
        ///.
        /// </summary>
        public static string ObjectGetAlert {
            get {
                return ResourceManager.GetString("ObjectGetAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///1. - get item by Id;
        ///2. - get all items;
        ///3. - add item;
        ///4. - remove item by Id;
        ///5. - edit item;
        ///
        ///0. - return to home screen.
        ///.
        /// </summary>
        public static string ObjectGetCommands {
            get {
                return ResourceManager.GetString("ObjectGetCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Obect was successfully removed:
        ///.
        /// </summary>
        public static string ObjectRemoveAlert {
            get {
                return ResourceManager.GetString("ObjectRemoveAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///1. - get product by Id;
        ///2. - get all products;
        ///3. - add product;
        ///4. - remove product by Id;
        ///5. - edit product;
        ///
        ///0. - return to home screen..
        /// </summary>
        public static string ProductGetCommands {
            get {
                return ResourceManager.GetString("ProductGetCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProductController
        ///
        ///(Body format: Id|Name|Energy|Protein|Fat|Carbohydrates)
        ///.
        /// </summary>
        public static string ProductInputHeader {
            get {
                return ResourceManager.GetString("ProductInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protein.
        /// </summary>
        public static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///1. - get reciept by Id;
        ///2. - get all reciepts;
        ///3. - reciept for last # days;
        ///4. - add reciept;
        ///5. - remove reciept by Id;
        ///6. - edit reciept;
        ///7. - create reciept(Format: VisitorId|Date);
        ///
        ///0. - return to home screen.
        ///.
        /// </summary>
        public static string RecieptGetCommands {
            get {
                return ResourceManager.GetString("RecieptGetCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check info:
        ///.
        /// </summary>
        public static string RecieptInfo {
            get {
                return ResourceManager.GetString("RecieptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check controller
        ///
        ///(Body format: Id|DishId|Quantity|CustomerId|Date_Order)
        ///Date format: dd-MM-yyyy-hh-mm-ss
        ///
        ///.
        /// </summary>
        public static string RecieptInputHeader {
            get {
                return ResourceManager.GetString("RecieptInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request body:.
        /// </summary>
        public static string RequestBody {
            get {
                return ResourceManager.GetString("RequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unexpected error.
        ///Try again later.
        ///.
        /// </summary>
        public static string UnexpectedAlert {
            get {
                return ResourceManager.GetString("UnexpectedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer name.
        /// </summary>
        public static string VisitorName {
            get {
                return ResourceManager.GetString("VisitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WarehouseController
        ///
        ///(Body format: Id|ProductId|Quantity)
        ///.
        /// </summary>
        public static string WarehouseInputHeader {
            get {
                return ResourceManager.GetString("WarehouseInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a controller:
        ///
        ///1. - product controller;
        ///2. - kitchen (dish) controller;
        ///3. - warehouse controller;
        ///4. - check controller;
        ///5. - fitness controlles;
        ///
        ///0.- exit.
        ///.
        /// </summary>
        public static string WelcomeScreen {
            get {
                return ResourceManager.GetString("WelcomeScreen", resourceCulture);
            }
        }
    }
}
